import Blog from "@/components/Blog";
import Books from "@/components/Books";
import Navigation from "@/components/Navigation";
import RelojEffect from "@/components/RelojEffect";
import RelojEf from "@/components/rolex";
import BooksContextProvider, { BookContext } from "@/context/BooksContextProvider";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navigation/>
        <BooksContextProvider>
        <Blog/>
        <RelojEffect/>
        <Books/>
      </BooksContextProvider>
     <RelojEf/>
      </main>
    </>
  );
}
