import Navigation from "@/components/atoms/Navigation";
import Books from "@/components/organisms/Books";
import BooksContextProvider from "@/context/BooksContextProvider";
import Head from "next/head";


export default function Home() {
  return (
    <>
      <Head>
        <title>Bloj</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/react.png" />
      </Head>

      <main>
           <Navigation/>
             <BooksContextProvider>
                <Books/>
             </BooksContextProvider>
      </main>
    </>
  );
}
