import Blog from "@/components/Blog";
import Navigation from "@/components/Navigation";
import BooksContextProvider from "@/context/BooksContextProvider";
import Head from "next/head";

const tiposDeRelojes = () => {
  return (
    <>
      <Head>
        <title>Tipo de Relojes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="bodyAnalogico">
        <Navigation/>
        <BooksContextProvider>
          <Blog/>   
        </BooksContextProvider>
      </div>
    </>
  )
}

export default tiposDeRelojes;
